spring.application.name=oauth

# GitHub OAuth2 Configuration
spring.security.oauth2.client.registration.github.client-id=Ov23liZGnFiDNjwk1aJq
spring.security.oauth2.client.registration.github.client-secret=0c1e14d2d7a8459c57d0193deadc7ed2228dc866
spring.security.oauth2.client.registration.github.scope=read:user,user:email
spring.security.oauth2.client.registration.github.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.security.oauth2.client.provider.github.authorization-uri=https://github.com/login/oauth/authorize
spring.security.oauth2.client.provider.github.token-uri=https://github.com/login/oauth/access_token
spring.security.oauth2.client.provider.github.user-info-uri=https://api.github.com/user
spring.security.oauth2.client.provider.github.user-name-attribute=id

# Server Configuration
server.port=8080
